"use client";

import { useState } from "react";

/* ── Output documents ── */

interface OutputDoc {
  id: string;
  company: string;
  fitScore: string;
  priority: string;
  color: string;
  description: string;
  contacts: number;
  cadences: number;
  touches: number;
  embedUrl: string | null;
}

const outputDocs: OutputDoc[] = [
  {
    id: "harness",
    company: "Harness",
    fitScore: "9/10",
    priority: "HIGH",
    color: "#7c6bc4",
    description:
      "Full pipeline output: forensic analysis, ICP profiles, scored leads (Jyoti Bansal, Sanjay Agarwal, Nick Durkin, Carlos Delatorre), and multi-channel cadences across Extended, Standard, and Compact sequences.",
    contacts: 4,
    cadences: 4,
    touches: 38,
    embedUrl: "https://docs.google.com/document/d/e/2PACX-1vRVEWb1bYnO9JR-kigxT60ARl2W5GNeUrfA_R0uT_ZKCaXtLppxheazzMbyAWoW0A/pub?embedded=true",
  },
  {
    id: "glean",
    company: "Glean",
    fitScore: "8/10",
    priority: "HIGH",
    color: "#2db87e",
    description:
      "Full pipeline output: forensic analysis of 100+ connector attack surface, ICP profiles, scored leads (Arvind Jain, Vishwanath TR, Tamar Yehoshua, Marc Wendling), and multi-channel cadences.",
    contacts: 4,
    cadences: 4,
    touches: 36,
    embedUrl: null,
  },
  {
    id: "jasper",
    company: "Jasper.ai",
    fitScore: "7/10",
    priority: "MED-HIGH",
    color: "#4a90d9",
    description:
      "Full pipeline output: forensic analysis of Canvas/Studio/extension surfaces, ICP profiles, scored leads (Timothy Young, Melody Meckfessel, Shane Orlick, Alex Barrera), and multi-channel cadences.",
    contacts: 4,
    cadences: 4,
    touches: 28,
    embedUrl: null,
  },
  {
    id: "ssi",
    company: "Safe Superintelligence (SSI)",
    fitScore: "1/10",
    priority: "SKIP",
    color: "#727782",
    description:
      "Disqualified. No product, no customers, no public-facing application. Pure foundational AI research with ~20 researchers. Nothing to test. Revisit only if/when they launch a commercial product.",
    contacts: 0,
    cadences: 0,
    touches: 0,
    embedUrl: null,
  },
];

/* ── Priority badge ── */

function PriorityBadge({ priority }: { priority: string }) {
  const styles: Record<string, { bg: string; text: string }> = {
    HIGH: { bg: "#2db87e20", text: "#1a7a4e" },
    "MED-HIGH": { bg: "#d4843e20", text: "#a0632a" },
    SKIP: { bg: "#72778220", text: "#727782" },
  };
  const s = styles[priority] || styles.SKIP;
  return (
    <span
      className="text-[0.6875rem] font-bold px-2 py-0.5 rounded uppercase tracking-wide"
      style={{ backgroundColor: s.bg, color: s.text }}
    >
      {priority}
    </span>
  );
}

/* ── Page ── */

export default function OutputsPage() {
  const [selectedDoc, setSelectedDoc] = useState<string>("harness");

  const current = outputDocs.find((d) => d.id === selectedDoc)!;

  return (
    <div className="max-w-[960px] mx-auto pb-12 space-y-8">
      {/* Header */}
      <div>
        <h1 className="font-sans text-[2rem] font-bold tracking-[-0.02em] text-on-surface">
          Pipeline Outputs
        </h1>
        <p className="text-on-surface-variant text-sm mt-1 max-w-[640px] leading-relaxed">
          Real campaign outputs generated by the Outbound Engine. Each document
          contains the full pipeline: forensic analysis, ICP profiles, scored
          leads, and multi-channel cadences.
        </p>
      </div>

      {/* Company selector */}
      <div className="flex gap-2 overflow-x-auto pb-1">
        {outputDocs.map((doc) => {
          const isActive = selectedDoc === doc.id;
          return (
            <button
              key={doc.id}
              type="button"
              onClick={() => setSelectedDoc(doc.id)}
              className={`flex items-center gap-2.5 px-4 py-2.5 rounded-xl text-sm font-medium shrink-0 transition-all ${
                isActive
                  ? "text-white shadow-lift"
                  : "bg-surface-container-lowest text-on-surface-variant shadow-ghost hover:shadow-lift"
              }`}
              style={isActive ? { backgroundColor: doc.color } : {}}
            >
              {doc.company}
              <PriorityBadge priority={doc.priority} />
            </button>
          );
        })}
      </div>

      {/* Output detail */}
      <div className="bg-surface-container-lowest rounded-xl shadow-ghost overflow-hidden">
        {/* Title bar */}
        <div
          className="px-6 py-4 flex items-center gap-4"
          style={{ borderBottom: `3px solid ${current.color}` }}
        >
          <div
            className="w-10 h-10 rounded-xl flex items-center justify-center text-white font-bold text-sm shrink-0"
            style={{ backgroundColor: current.color }}
          >
            <span className="material-symbols-outlined" style={{ fontSize: 20 }}>
              domain
            </span>
          </div>
          <div className="flex-1 min-w-0">
            <h2 className="text-base font-semibold text-on-surface">
              {current.company}
            </h2>
            <p className="text-xs text-on-surface-variant">
              Full Pipeline Output
            </p>
          </div>
          <div className="flex items-center gap-3">
            <div className="text-right">
              <div className="text-lg font-bold text-on-surface">{current.fitScore}</div>
              <div className="text-[0.6875rem] text-on-surface-variant">Fit Score</div>
            </div>
          </div>
        </div>

        {/* Stats row */}
        {current.contacts > 0 && (
          <div className="px-6 py-3 border-b border-outline-variant/15 flex gap-6">
            <div className="flex items-center gap-2">
              <span className="material-symbols-outlined text-primary" style={{ fontSize: 16 }}>
                people
              </span>
              <span className="text-sm text-on-surface font-medium">{current.contacts}</span>
              <span className="text-xs text-on-surface-variant">contacts</span>
            </div>
            <div className="flex items-center gap-2">
              <span className="material-symbols-outlined text-primary" style={{ fontSize: 16 }}>
                route
              </span>
              <span className="text-sm text-on-surface font-medium">{current.cadences}</span>
              <span className="text-xs text-on-surface-variant">cadences</span>
            </div>
            <div className="flex items-center gap-2">
              <span className="material-symbols-outlined text-primary" style={{ fontSize: 16 }}>
                touch_app
              </span>
              <span className="text-sm text-on-surface font-medium">{current.touches}</span>
              <span className="text-xs text-on-surface-variant">touches</span>
            </div>
          </div>
        )}

        {/* Description */}
        <div className="px-6 py-4 border-b border-outline-variant/15">
          <p className="text-sm text-on-surface-variant leading-relaxed">
            {current.description}
          </p>
        </div>

        {/* Embedded Google Doc or placeholder */}
        {current.embedUrl ? (
          <div className="w-full" style={{ height: "80vh" }}>
            <iframe
              src={current.embedUrl}
              className="w-full h-full border-0"
              title={`${current.company} Pipeline Output`}
              allowFullScreen
            />
          </div>
        ) : current.priority === "SKIP" ? (
          <div className="flex flex-col items-center justify-center py-16 text-center">
            <span className="material-symbols-outlined text-outline mb-3" style={{ fontSize: 36 }}>
              block
            </span>
            <p className="text-sm font-medium text-on-surface mb-1">
              Account Disqualified
            </p>
            <p className="text-xs text-on-surface-variant max-w-[400px]">
              {current.description}
            </p>
          </div>
        ) : (
          <div className="flex flex-col items-center justify-center py-16 text-center">
            <span className="material-symbols-outlined text-outline mb-3" style={{ fontSize: 36 }}>
              description
            </span>
            <p className="text-sm font-medium text-on-surface mb-1">
              Google Doc coming soon
            </p>
            <p className="text-xs text-on-surface-variant">
              Document will be embedded here once published.
            </p>
          </div>
        )}
      </div>
    </div>
  );
}
